name: raya_keyta_quiz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
    confetti: ^0.7.0
    google_fonts: ^6.1.0
    flutter_animate: ^4.5.0
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/stickers/sticker1 (1).png
    - assets/stickers/sticker2 (1).png
    - assets/stickers/sticker5-200px.png
    - assets/stickers/sticker3100px.png
    - assets/stickers/stiker4.png
    - assets/audio/KlavdiiaPetrivna.mp3
